2020-03-29 13:36:15,341 [ERROR   ][i3pystatus.weather.Weather 76] Exception in Thread-3 at Sun 29 Mar 2020 01:36:15 PM -03, module Weather
Traceback (most recent call last):
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/core/threading.py", line 68, in __call__
    self.workload()
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/core/modules.py", line 285, in __call__
    self.run()
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/core/util.py", line 348, in wrapper
    return method(*args, **kwargs)
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/weather/__init__.py", line 144, in run
    data = self.backend.weather_data()
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/core/util.py", line 348, in wrapper
    return method(*args, **kwargs)
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/weather/weathercom.py", line 84, in weather_data
    doc = ElementTree.XML(xml)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
2020-03-29 13:38:41,953 [ERROR   ][i3pystatus.weather.Weather 76] Exception in Thread-3 at Sun 29 Mar 2020 01:38:41 PM -03, module Weather
Traceback (most recent call last):
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/core/threading.py", line 68, in __call__
    self.workload()
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/core/modules.py", line 285, in __call__
    self.run()
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/core/util.py", line 348, in wrapper
    return method(*args, **kwargs)
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/weather/__init__.py", line 144, in run
    data = self.backend.weather_data()
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/core/util.py", line 348, in wrapper
    return method(*args, **kwargs)
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/weather/weathercom.py", line 84, in weather_data
    doc = ElementTree.XML(xml)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
2020-03-29 13:49:35,933 [ERROR   ][i3pystatus.weather.Weather 76] Exception in Thread-3 at Sun 29 Mar 2020 01:49:35 PM -03, module Weather
Traceback (most recent call last):
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/core/threading.py", line 68, in __call__
    self.workload()
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/core/modules.py", line 285, in __call__
    self.run()
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/core/util.py", line 348, in wrapper
    return method(*args, **kwargs)
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/weather/__init__.py", line 144, in run
    data = self.backend.weather_data()
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/core/util.py", line 348, in wrapper
    return method(*args, **kwargs)
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/weather/weathercom.py", line 84, in weather_data
    doc = ElementTree.XML(xml)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
2020-03-29 14:06:04,650 [ERROR   ][i3pystatus.weather.Weather 76] Exception in Thread-3 at Sun 29 Mar 2020 02:06:04 PM -03, module Weather
Traceback (most recent call last):
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/core/threading.py", line 68, in __call__
    self.workload()
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/core/modules.py", line 285, in __call__
    self.run()
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/core/util.py", line 348, in wrapper
    return method(*args, **kwargs)
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/weather/__init__.py", line 144, in run
    data = self.backend.weather_data()
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/core/util.py", line 348, in wrapper
    return method(*args, **kwargs)
  File "/home/colps/.local/lib/python3.8/site-packages/i3pystatus/weather/weathercom.py", line 84, in weather_data
    doc = ElementTree.XML(xml)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
